version: "3"

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.3
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.rule: Host(`dashboard.docker.localhost`)
      traefik.http.routers.dashboard.service: api@internal
  redis:
    image: redislabs/rejson:latest
    container_name: rejson
    hostname: rejson
    networks:
      - datalayer
  unsplash:
    image: advtr/unsplash-proxy:main
    environment:
      - LOGLEVEL=silly
      - UNSPLASH_API_KEY=${UNSPLASH_API_KEY}
      - CACHE_HOST=rejson
      - CACHE_PORT=6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unsplash.rule=Host(`api.localhost`) && PathPrefix(`/assets/`)"
      - "traefik.http.routers.unsplash.entrypoints=web"
      - "traefik.http.routers.unsplash.service=unsplash"
      - "traefik.http.routers.unsplash.middlewares=unsplash@docker"
      - "traefik.http.services.unsplash.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.unsplash.stripprefix.prefixes=/assets"
    networks:
      - web
      - datalayer

networks:
  web:
    external: true
  datalayer:
