# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
      - 'releases/**'
      # Add mine here since I'm the only dev
      - 'harrytwright/**'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '16'
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Run Jest
        run: npm run test
  audit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '16'
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Check production deps
        run: npm audit --omit dev
