# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: StoryBook

on:
  push:
    branches:
      - main
      - 'harrytwright/**'
    paths-ignore:
      - 'README.md'

jobs:
  deploy-docs:
    runs-on: macos-latest
    if: "!contains(github.event.commits[0].message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Build storybook
        run: npm run build:storybook -- -o ./build
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy:gh-pages -- -d ./build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
